"""C6 — Phase-A humanizer sim (no telephony).

Generates candidate spoken lines for the receptionist situations (C1, few-shot
from the example bank), then scores each against the R1-R9 naturalness rubric
(C2). Prints a per-situation report (scores, pronunciation flags, suggestions)
and the overall human-likeness — so we improve the lines cheaply before any
real call. All data is synthetic (no PII).

Usage:
    python -m scripts.humanizer_sim
    python -m scripts.humanizer_sim --situations greeting,offer_slots
"""
import sys

from agent.eval import naturalness
from agent.eval.example_bank import ExampleBank
from agent.i18n import te_gen

# English situation descriptions (the agent's Telugu is generated by Gemini).
SITUATIONS = {
    "greeting": "She picks up the phone at {clinic} and warmly greets the caller, then asks how she can help.",
    "restate_issue": "The caller told her their need; she reflects it back to confirm she understood: an appointment for {issue}.",
    "thinking_filler": "She's looking up available slots; she fills the silence so the caller isn't left hanging.",
    "offer_slots": "She offers two open slots — tomorrow morning at {time}, or afternoon at {time} — and asks which suits.",
    "close_booked": "She wraps up after booking tomorrow at {time}: come a little early, call again if any doubt, thanks.",
    "anxious_reassure": "The caller sounds anxious; she reassures them warmly that she'll arrange the appointment right away. NO medical advice.",
    "angry_validate": "The caller is upset about an inconvenience; she acknowledges, apologises, and says she'll fix it now.",
    "relay_to_doctor": "The caller mentioned a problem; she says she will inform the doctor about {name} and get back. NO advice/diagnosis.",
}


def run(situation_keys=None) -> int:
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass
    bank = ExampleBank()
    sits = {k: SITUATIONS[k] for k in (situation_keys or SITUATIONS)}

    print(f"-- Phase-A sim: generating {len(sits)} lines (Gemini, few-shot from bank: "
          f"{len(bank.all())} examples) --")
    lines = te_gen.generate_lines(sits, bank=bank)

    overall = []
    for key, desc in sits.items():
        line = lines.get(key, "")
        transcript = [
            {"role": "context", "text": desc},
            {"role": "agent", "text": line},
        ]
        try:
            score = naturalness.score_naturalness(transcript)
        except Exception as e:  # noqa: BLE001
            print(f"\n[{key}] judge failed: {e}")
            continue
        hl = score.get("human_likeness")
        overall.append(hl if isinstance(hl, (int, float)) else 0)
        print(f"\n[{key}] human_likeness={hl}")
        print(f"  line: {line}")
        if score.get("pronunciation_flags"):
            print(f"  ROMANIZED (will be spelled by TTS): {score['pronunciation_flags']}")
        sc = score.get("scores", {})
        if sc:
            print(f"  scores: {sc}")
        for s in score.get("suggestions", [])[:3]:
            print(f"  fix: {s}")

    if overall:
        print(f"\n== overall human_likeness avg: {sum(overall)/len(overall):.2f} / 5 "
              f"({len(overall)} situations) ==")
    return 0


def _parse_argv(argv):
    keys = None
    for a in argv:
        if a.startswith("--situations"):
            val = a.split("=", 1)[1] if "=" in a else None
            if val:
                keys = [k.strip() for k in val.split(",") if k.strip()]
    # also support "--situations a,b" as two tokens
    if "--situations" in argv:
        i = argv.index("--situations")
        if i + 1 < len(argv) and not argv[i + 1].startswith("--"):
            keys = [k.strip() for k in argv[i + 1].split(",") if k.strip()]
    return keys


if __name__ == "__main__":
    raise SystemExit(run(_parse_argv(sys.argv[1:])))
